# Codecov configuration - require 75% overall coverage by default
# Adjust target as needed

coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 0%

# Fail CI if Codecov upload/report indicates a problem
require_ci_to_pass: yes

# Exclude folders from Codecov
ignore:
  - "**/tests/*"
  - "**/test/*"
  - "**/__tests__/*"
  - "**/test_*.go"
  - "**/*_test.go"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "docs/*"
  - ".github/*"
  - "scripts/*"
  - "tools/*"
  - "frontend/node_modules/*"
  - "frontend/dist/*"
  - "frontend/coverage/*"
  - "backend/cmd/seed/*"
  - "backend/cmd/api/*"
  - "backend/data/*"
  - "backend/coverage/*"
  - "backend/internal/services/docker_service.go"
  - "backend/internal/api/handlers/docker_handler.go"
  - "*.md"
